// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZf__hVFusemquTZeZSkJYhiMk3RfxtHg',
    appId: '1:653672261937:web:b276bd17917cd6b6ffa810',
    messagingSenderId: '653672261937',
    projectId: 'mynotes-f-h-a',
    authDomain: 'mynotes-f-h-a.firebaseapp.com',
    storageBucket: 'mynotes-f-h-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKh9Xdfm6BEH1s0vNRFP5po3byN4W8nO0',
    appId: '1:653672261937:android:1d045be8ff0ffa42ffa810',
    messagingSenderId: '653672261937',
    projectId: 'mynotes-f-h-a',
    storageBucket: 'mynotes-f-h-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxvXvSkZOB14CfceHgfrPzCh1Irtcl3V0',
    appId: '1:653672261937:ios:5601723bde258ce4ffa810',
    messagingSenderId: '653672261937',
    projectId: 'mynotes-f-h-a',
    storageBucket: 'mynotes-f-h-a.appspot.com',
    iosClientId: '653672261937-b0mi92duedpiqrtoivullg9ovocpa773.apps.googleusercontent.com',
    iosBundleId: 'com.ohitworks.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxvXvSkZOB14CfceHgfrPzCh1Irtcl3V0',
    appId: '1:653672261937:ios:5601723bde258ce4ffa810',
    messagingSenderId: '653672261937',
    projectId: 'mynotes-f-h-a',
    storageBucket: 'mynotes-f-h-a.appspot.com',
    iosClientId: '653672261937-b0mi92duedpiqrtoivullg9ovocpa773.apps.googleusercontent.com',
    iosBundleId: 'com.ohitworks.mynotes',
  );
}
